#!/bin/sh
# file2dataurl

VERSION='1.0.0'

file2dataurl_main() {
	trap _exit INT TERM

	e_args=16
	e_no_file=17

	scriptinv="$( basename "$0" )"
	scriptpath="$( readlink -f "$0" )"
	scriptname="$( basename "$scriptpath" )"

	while getopts hv opt
	do
		case $opt in
			h) cmd=help ;;
			v) cmd=version ;;
			*) _invalid_opt ;;
		esac
	done

	shift "$(( OPTIND - 1 ))"

	[ -z "$cmd" ] && cmd="process"

	case "$cmd" in
		help|process|version) "file2dataurl_$cmd" "$@" ;;
		*) _invalid_cmd ;;
	esac

	_exit
}

file2dataurl_help() {
cat <<USAGE
$scriptname $VERSION

USAGE: $scriptinv [<options>] <file>

Convert file to base64 data URL.

OPTIONS:

	-h        Show this help screen.
	-v        Show script name and version number.

USAGE
}

file2dataurl_process() {
	file="$1"
	[ ! -f "$file" ] && _fatal $e_no_file "No such file: $file"
	mime="$( file -b --mime-type "$file" )"
	_echo "data:${mime};base64,$( base64 "$file" | sed -E 's/=+$//' )"
}

file2dataurl_version() {
	_echo "$scriptname $VERSION"
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

_exit() {
	exit_code=$?
	exit $exit_code
}

_fatal() {
	exit_code="$1"
	shift
	_error "$@"
	exit "$exit_code"
}

_invalid_cmd() {
	_error "Invalid command: $cmd"
	_echo
	file2dataurl_help
	exit $e_args
}

_invalid_opt() {
	_error "Invalid option: $opt"
	_echo
	file2dataurl_help
	exit $e_args
}

file2dataurl_main "$@"
